# Generated by Django 5.0 on 2024-01-13 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_rename_digital_product_makeup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='makeup',
            new_name='body',
        ),
    ]
